export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './register/Register'
export { default as Search } from './Search'
export { default as Profile } from './Profile'
export { default as NotFound } from './NotFound'
export { default as CreateProfile } from './register/CreateUserProfile'
export { default as CreateNewRestaurant } from './Restaurant/CreateNewRestaurant'
// export { default as Restaurants } from './Restaurant/Restaurants'
